name: gastos_ruth
description: "Aplicación para administrar gastos e ingresos"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  pdf: ^3.10.4
  printing: ^5.11.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#009688"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
