name: mi_presupuesto
description: "Aplicación de control de gastos Gastos Ruth"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  pdf: ^3.10.8
  printing: ^5.13.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1" # <- Agrégalo aquí abajo junto a los demás

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#009688"
  adaptive_icon_foreground: "assets/app_icon.png"
